### ISSUE TITLE
Failing during gradle multi-project scan

### ISSUE THREAD

**Issue by JRemitz** [fossas/fossa-cli#135]
Hi, I'm trying to scan a gradle multi-project.  `fossa init` finds the primary build.gradle at the root level and gets to that task, however the task fails with the following:

```⡿ Running module analysis (5/5): build.gradle panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fossas/fossa-cli/module.ReadLocator(0xc42049340f, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/module/locator.go:45 +0x118
github.com/fossas/fossa-cli/module.ReadImportPath(0xc420493400, 0x130, 0x1, 0x1, 0x2)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/module/locator.go:66 +0xf1
github.com/fossas/fossa-cli/builders.computeImportPaths(0xc4204c6000, 0x37a, 0x471, 0x0, 0xc4204a2000, 0x2)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/common.go:201 +0x390
github.com/fossas/fossa-cli/builders.(*GradleBuilder).Analyze(0xc420316000, 0xc4200a7630, 0xd, 0xb6bbba, 0x6, 0xc4203f8e40, 0x28, 0xc4203f8e10, 0x28, 0x0, ...)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/gradle.go:131 +0xd12
main.defaultCmd(0xc420128c60)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:245 +0x76b
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction(0xa45200, 0xb995d0, 0xc420128c60, 0xc420084840, 0x0)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:492 +0x7c
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run(0xc4200b1ba0, 0xc42009a020, 0x2, 0x2, 0x0, 0x0)
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:264 +0x5ee
main.main()
        /home/leo/src/gopath/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:147 +0x2058
```

Not sure if related directly to the multi-project or something else with the initialization?  Here's the task in the `.fossa.yml`:

```  - name: batch:compile
    path: build.gradle
    type: gradle
    options:
      go:
        allowunresolved: false
      python:
        strategy: ""
      gradle:
        task: ""
        configuration: ""
      maven:
        settings: ""
      nuget:
        targetframework: ""
```
I was able to build one of the sub-projects by referencing that build.gradle directly, but the other four failed with similar errors.

**Comment by ilikebits** [comment]
Thanks for reporting! What version of `fossa` are you using?

The stack trace is interesting -- it looks like something is calling the analyser on initialisation and the dependency path data computation is causing it to break. cc @xizhao who wrote the Gradle analyser.

**Comment by JRemitz** [comment]
FOSSA version: `fossa-cli version 0.6.0-alpha.3 (revision 5f0299b9450d7b00a20b3ecba99e6f053bddf9c7 compiled with go version go1.10.1 linux/amd64)`

Alpine version: `3.7.0`

Gradle version: `Gradle 4.0.1`

Java version: `1.8.0.151`

**Comment by zlav** [comment]
This issue is now outdated. If this issue is still valid in FOSSA CLI v3 please reopen the issue and we will address it.
