### ISSUE TITLE
0.6.2 fatal error: runtime: out of memory during analysis that passed on 0.5.1

### ISSUE THREAD

**Issue by corbin-coleman** [fossas/fossa-cli#147]
When running `fossa analyze --branch={branch} --allow-unresolved --debug` using `0.6.2` I get a `fatal error: runtime: out of memory`.

Full error message:
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb7d153, 0x16)
	/usr/lib/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc659930000, 0x38e40000, 0xfabd00, 0xfc4e38)
	/usr/lib/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0xfab520, 0x38e40000, 0x7f20194dff78)
	/usr/lib/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0xfab520, 0x1c71b, 0x0)
	/usr/lib/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xfab520, 0x1c71b, 0xfc4e48, 0x7f201bffede8)
	/usr/lib/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xfab520, 0x1c71b, 0xffffffffffff0100, 0x7f201bffee18)
	/usr/lib/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xfab520, 0x1c71b, 0x7f201b010100, 0x415bec)
	/usr/lib/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x38e36000, 0x450001, 0x7f2023de96c8)
	/usr/lib/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/lib/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:363 fp=0xc42064f8b8 sp=0xc42064f8b0 pc=0x454480
runtime.mallocgc(0x38e36000, 0xaee6a0, 0xb6db01, 0x2)
	/usr/lib/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc42064f958 sp=0xc42064f8b8 pc=0x4121c2
runtime.growslice(0xaee6a0, 0xc6064ce000, 0xa1d040, 0xa1d071, 0xa1d39f, 0xc420432308, 0x1c, 0xc420432300)
	/usr/lib/go/src/runtime/slice.go:179 +0x14a fp=0xc42064f9c0 sp=0xc42064f958 pc=0x440d7a
github.com/fossas/fossa-cli/builders.getGoImportsRecurse(0xc4200ea2a0, 0xc4200253a0, 0x5, 0xb70299, 0x6, 0xc420432308, 0x1c, 0xc420432300, 0x24, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/golang.go:465 +0x346 fp=0xc42064fbf8 sp=0xc42064f9c0 pc=0x90ef96
github.com/fossas/fossa-cli/builders.getGoImportsRecurse(0xc4200ea2a0, 0xc4200253a0, 0x5, 0xb70299, 0x6, 0xc420432308, 0x1c, 0xc420432300, 0x24, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/golang.go:461 +0x1fc fp=0xc42064fe30 sp=0xc42064fbf8 pc=0x90ee4c
github.com/fossas/fossa-cli/builders.getGoImportsRecurse(0xc4200ea2a0, 0xc4200253a0, 0x5, 0xb70299, 0x6, 0xc420432308, 0x1c, 0xc420432300, 0x24, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/golang.go:461 +0x1fc fp=0xc420650068 sp=0xc42064fe30 pc=0x90ee4c
github.com/fossas/fossa-cli/builders.getGoImportsRecurse(0xc4200ea2a0, 0xc4200253a0, 0x5, 0xb70299, 0x6, 0xc420432308, 0x1c, 0xc420432300, 0x24, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/golang.go:461 +0x1fc fp=0xc4206502a0 sp=0xc420650068 pc=0x90ee4c
github.com/fossas/fossa-cli/builders.getGoImports(0xc4200ea2a0, 0xc4200253a0, 0x5, 0xb70299, 0x6, 0xc420432308, 0x1c, 0xc420432300, 0x24, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/golang.go:477 +0x100 fp=0xc4206504c0 sp=0xc4206502a0 pc=0x90f4f0
github.com/fossas/fossa-cli/builders.(*GoBuilder).IsBuilt(0xc4200ea2a0, 0xc4200253a0, 0x5, 0xb70299, 0x6, 0xc420432308, 0x1c, 0xc420432300, 0x24, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/builders/golang.go:743 +0x15e fp=0xc420650698 sp=0xc4206504c0 pc=0x91282e
main.doAnalyze(0xc4200ec400, 0x9, 0x9, 0xc420025301, 0x6, 0xc420023360, 0x1a, 0xc42008afc0, 0x28)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/cmd/fossa/analyze.go:73 +0x360 fp=0xc420650a88 sp=0xc420650698 pc=0x9c4ad0
main.analyzeCmd(0xc4200e0dc0)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/cmd/fossa/analyze.go:23 +0x109 fp=0xc420650e98 sp=0xc420650a88 pc=0x9c3ee9
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction(0xa49d20, 0xb9e1c0, 0xc4200e0dc0, 0xc42006c800, 0x0)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:492 +0x7c fp=0xc420650ec0 sp=0xc420650e98 pc=0x87dabc
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.Command.Run(0xb710cd, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb8002c, 0x1a, 0x0, ...)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/command.go:210 +0xa36 fp=0xc420651130 sp=0xc420650ec0 pc=0x87ed76
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run(0xc42008f860, 0xc42001e1e0, 0x5, 0x5, 0x0, 0x0)
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:255 +0x6a0 fp=0xc420651308 sp=0xc420651130 pc=0x87be90
main.main()
	/home/leo/src/gopath/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:143 +0x1f21 fp=0xc420651f88 sp=0xc420651308 pc=0x9c9e01
runtime.main()
	/usr/lib/go/src/runtime/proc.go:198 +0x212 fp=0xc420651fe0 sp=0xc420651f88 pc=0x42cc52
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420651fe8 sp=0xc420651fe0 pc=0x457011
```

I'm running inside a Docker container based from `ubuntu xenial` that installs node 10, fossa-cli 0.6.2, and Go 1.10.2. When I run this same command, minus `--branch={branch}` as it's not available in older versions, in a container running fossa-cli 0.5.1 the analysis runs completely fine. Running on 0.6.2 without `--branch={branch}` still gives the same error message.

**Comment by ilikebits** [comment]
This is strange. The stack trace makes me think this is a memory issue instead of infinite recursion. This might be a stupid question, but does this execute on a box with more memory?

I'm working on a refactor of the Go analysers right now, with much better memory performance. It should be ready by the end of the week. I'll ping this thread to let you know.

**Comment by corbin-coleman** [comment]
I haven't tried running this on a larger machine yet. So, I can't speak on that currently. I would imagine that would have a benefit. I can try to make sure later on though.

**Comment by ilikebits** [comment]
Closing due to inactivity. Please re-open if this still affects you in `v0.7.0`.
