### ISSUE TITLE
fossa-cli version 0.7.6 - panic: runtime error: slice bounds out of range - java maven project

### ISSUE THREAD

**Issue by Michael-Frank** [fossas/fossa-cli#252]
**Describe the bug**
```
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/fossas/fossa-cli/buildtools/maven.ParseDependencyTree
```
**To Reproduce**
1. checkout https://github.com/Michael-Frank/jmh-Introduction.git
2. manually downloaded https://github.com/fossas/fossa-cli/releases/download/v0.7.6/fossa-cli_0.7.6_windows_amd64.zip
3.for first tests extracted zip contents into project root folder 
4. executed `fossa.exe -o`

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag
```
DEBUG done running callers=[/home/fossa/go/src/github.com/fossas/fossa-cli/exec/run.go:github.com/fossas/fossa-cli/exec.Run:63 /home/fossa/go/src/github.com/fossas/fossa-cli/buildtools/maven/maven.go:github.com/fossas/fossa-cli/buildtools/maven.(*Maven).DependencyTree:97 /home/fossa/go/src/github.com/fossas/fossa-cli/analyzers/maven/maven.go:github.com/fossas/fossa-cli/analyzers/maven.(*Analyzer).Analyze:137 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Do:122 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Run:48 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:main.Run:75 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction:490 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run:264 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:main.main:47] stderr= stdout=[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JMH benchmarks: intro, basic benchmarks, algorithms and some architectural support benchmarks 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jmh-introduction ---
[INFO] de.frank:jmh-introduction:jar:1-SNAPSHOT
[INFO] +- org.openjdk.jmh:jmh-core:jar:1.21:compile
[INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:4.6:compile
[INFO] |  \- org.apache.commons:commons-math3:jar:3.2:compile
[INFO] +- org.openjdk.jmh:jmh-generator-annprocess:jar:1.21:provided
[INFO] +- it.unimi.dsi:dsiutils:jar:2.4.2:compile
[INFO] |  +- it.unimi.dsi:fastutil:jar:8.1.0:compile
[INFO] |  +- com.martiansoftware:jsap:jar:2.1:compile
[INFO] |  +- com.google.guava:guava:jar:23.2-jre:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.18:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.3:runtime
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:runtime
[INFO] |  +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- commons-io:commons-io:jar:2.5:compile
[INFO] |  \- commons-collections:commons-collections:jar:20040616:compile
[INFO] +- org.springframework:spring-core:jar:5.0.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-jcl:jar:5.0.8.RELEASE:compile
[INFO] +- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- de.vandermeer:asciitable:jar:0.3.2:compile
[INFO] |  +- de.vandermeer:ascii-utf-themes:jar:0.0.1:compile
[INFO] |  |  \- de.vandermeer:skb-interfaces:jar:0.0.1:compile
[INFO] |  |     +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  |     +- org.antlr:ST4:jar:4.0.8:compile
[INFO] |  |     |  \- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] |  |     \- org.antlr:antlr4:jar:4.5.1:compile
[INFO] |  \- de.vandermeer:char-translation:jar:0.0.2:compile
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.587 s
[INFO] Finished at: 2018-09-05T19:41:13+02:00
[INFO] Final Memory: 13M/210M
[INFO] ------------------------------------------------------------------------

panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/fossas/fossa-cli/buildtools/maven.ParseDependencyTree(0xc042334000, 0xc0c, 0xc042198a40, 0x4, 0x4, 0x0, 0x0, 0xc042423ce0)
        /home/fossa/go/src/github.com/fossas/fossa-cli/buildtools/maven/maven.go:132 +0x4cf
github.com/fossas/fossa-cli/buildtools/maven.(*Maven).DependencyTree(0xc04206a000, 0xc042423ce0, 0x1, 0xc042071ae0, 0x19, 0x489, 0x41081f, 0x2, 0x3, 0xa994c0, ...)
        /home/fossa/go/src/github.com/fossas/fossa-cli/buildtools/maven/maven.go:106 +0x1d8
github.com/fossas/fossa-cli/analyzers/maven.(*Analyzer).Analyze(0xc04206a000, 0x1, 0x0, 0x0, 0xc042071ae0, 0x19, 0xc042423ce0)
        /home/fossa/go/src/github.com/fossas/fossa-cli/analyzers/maven/maven.go:137 +0xdd
github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Do(0xc042184150, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:122 +0x969
github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Run(0xc0420a8dc0, 0x0, 0x0)
        /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:48 +0xb1
main.Run(0xc0420a8dc0, 0xc0420a8dc0, 0xc042091d2f)
        /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:75 +0x83
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction(0xaac240, 0xbf6850, 0xc0420a8dc0, 0xc0420a26c0, 0x0)
        /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:490 +0xcf
github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run(0x10172a0, 0xc04206e080, 0x3, 0x4, 0x0, 0x0)
        /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:264 +0x5f5
main.main()
        /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:47 +0x5c
```
2. The output of `fossa --version`
```
fossa-cli version 0.7.6 (revision a35fd0b5e1e910757c42f0a8bc0606cf9303b952 compiled with go version go1.10.3 linux/amd64)
```

3.  The project's configuration file (usually `.fossa.yml`)
```yml
version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: https://github.com/Michael-Frank/jmh-Introduction.git
analyze:
  modules:
  - name: de.frank:jmh-introduction
    type: mvn
    target: de.frank:jmh-introduction
    path: .
```
4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository)
https://github.com/Michael-Frank/jmh-Introduction

**Environment (please complete the following information):**
windows 10 64bit + powershell

**Comment by liftM** [comment]
Thanks for reporting this. This looks like an issue with how we filter command output, and I think we'll resolve this in a method to #155 (by writing output to a file instead of filtering).

**Comment by liftM** [comment]
Are you able to reproduce this in Linux? I suspect this might be a Windows-specific problem.

**Comment by Michael-Frank** [comment]
sorry, got no linx at hand at the moment

**Comment by Michael-Frank** [comment]
Tried running it in Windows Subsystem for Unix (WSU Ubuntu) . Installed with:
```
curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
```
But got a different error:
```
DEBUG done running callers=[/home/fossa/go/src/github.com/fossas/fossa-cli/exec/run.go:github.com/fossas/fossa-cli/exec.Run:63 /home/fossa/go/src/github.com/fossas/fossa-cli/buildtools/maven/maven.go:github.com/fossas/fossa-cli/buildtools/maven.(*Maven).DependencyTree:97 /home/fossa/go/src/github.com/fossas/fossa-cli/analyzers/maven/maven.go:github.com/fossas/fossa-cli/analyzers/maven.(*Analyzer).Analyze:137 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Do:122 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Run:48 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction:490 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/command.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.Command.Run:210 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run:255 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:main.main:47] stderr= stdout=
FATAL Could not analyze: fork/exec : permission denied callers=[/home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Do:124 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Run:48 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction:490 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/command.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.Command.Run:210 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run:255 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:main.main:47]
```

**Comment by Michael-Frank** [comment]
I noticed two things:

#### 1. Proabale RootCause: bug in buildtools/maven/maven.go - Split must not only consider *nix `\n` linebreaks but must be able to handle windows linebreaks `\r\n` as well.
This line:
https://github.com/fossas/fossa-cli/blame/v0.7.6/buildtools/maven/maven.go#L116
```go
for _, line := range strings.Split(stdin, "\n") {
```

Should probably be:
```go
splitReg:=regexp.MustCompile("\r?\n")
for _, line := range splitReg.Split(stdin, -1) {
```

Minimal working example:
```go
package main
import ("fmt" "regexp" )
func main() {
    fromStdIn:= "[INFO] Windows line\r\n[INFO] UNIX Line\n[INFO]  ---"
    splitReg:=regexp.MustCompile("\r?\n")
    for _, line := range splitReg.Split(fromStdIn, -1) {
      fmt.Println("Line: " + line)
    }
}
```

#### 2.) Seams like there is a length check missing when truncating the `filteredLines `array
https://github.com/fossas/fossa-cli/blame/v0.7.6/buildtools/maven/maven.go#L130-L133
```go
	filteredLines = filteredLines[1:]
```

**Comment by Michael-Frank** [comment]
@liftM Any update?
