### ISSUE TITLE
fossa v1.1.4 Homebrew install - No such file or directory - fossa-cli

### ISSUE THREAD

**Issue by dpjtaylor** [fossas/fossa-cli#651]
**Describe the bug**
When running `brew upgrade fossas/tap/fossa` the upgrade fails with an error `No such file or directory - fossa-cli`

<img width="974" alt="Screenshot 2021-02-14 at 08 57 55" src="https://user-images.githubusercontent.com/47084657/107872587-356d1d00-6ea3-11eb-8c70-eb645ed1c9ab.png">

It looks like this is because the tap [here](https://github.com/fossas/homebrew-tap/blob/master/fossa.rb) is configured to install a binary called `fossa-cli`, but the binary in the release 1.1.4 tar file [here](https://github.com/fossas/fossa-cli/releases/tag/v1.1.4) is called `fossa`.

<img width="340" alt="Screenshot 2021-02-14 at 09 09 54" src="https://user-images.githubusercontent.com/47084657/107872770-774a9300-6ea4-11eb-895c-657c73859ba4.png">

fossa-bot` updated the tap with [this commit](https://github.com/fossas/homebrew-tap/commit/06452263353f5438f84b8b1a7487f9481f99d50a#diff-a74fefab164fb062b1a5603e1a828450a0d5c32fa29382f80e3035ee3a7f9037), but not quite sure how that all joins up (not being familiar with fossa-bot)

```
  def install
    bin.install "fossa-cli"
  end
```

**To Reproduce**
Run `brew upgrade fossas/tap/fossa`

**Expected behavior**
Installs fossa client v1.1.4

**Debugging information**
See screenshot above

**Environment (please complete the following information):**
 - OS: Mac
 - Are you running in CI?: Both on CI and developer Macbook
 - Are you running in a Docker image?: No

**Additional context**
N/A

**Comment by commjoen** [comment]
I get a similar issue when trying to run `brew install fossas/tap/fossa` It gives:

```sh
==> Installing fossa from fossas/tap
==> Downloading https://github.com/fossas/fossa-cli/releases/download/v1.1.5/fossa-cli_1.1.5_darwin_amd64.tar.gz
==> Downloading from https://github-releases.githubusercontent.com/116995448/5f8e4a00-71d7-11eb-8422-fdf5950db0a6?X-Amz-Algorithm=AWS4-HMAC-SHA
######################################################################## 100.0%
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - fossa-cli```

should i create a new ticket for this?

**Comment by dpjtaylor** [comment]
This looks like the same issue to me. I put up a pull request, but need some help from a maintainer.

**Comment by dpjtaylor** [comment]
If other users are affected you can use this approach to install the CLI without brew,
```
curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
```
https://docs.fossa.com/docs/importing-a-project

**Comment by Walther** [comment]
This also breaks `brew cleanup`:
```
brew cleanup -d
# skipping irrelevant entries
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/fossas/homebrew-tap/fossa.rb
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:253:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:206:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:153:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:153:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:366:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:388:in `from_rack'
/opt/homebrew/Library/Homebrew/cleanup.rb:85:in `stale_formula?'
/opt/homebrew/Library/Homebrew/cleanup.rb:58:in `stale?'
/opt/homebrew/Library/Homebrew/cleanup.rb:321:in `block in cleanup_cache'
/opt/homebrew/Library/Homebrew/cleanup.rb:304:in `each'
/opt/homebrew/Library/Homebrew/cleanup.rb:304:in `cleanup_cache'
/opt/homebrew/Library/Homebrew/cleanup.rb:192:in `clean!'
/opt/homebrew/Library/Homebrew/cmd/cleanup.rb:58:in `cleanup'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

This is not great, considering `brew` auto-cleans by default:
```
==> `brew cleanup` has not been run in 30 days, running now...
```

Would appreciate tips on how to fix this in a way that gets `brew` back into a happy state 🙇‍♂️  Thanks!

**Comment by sk-** [comment]
For those affected, you can run `brew edit fossas/tap/fossa` and fix the binary.

**Comment by zlav** [comment]
Hi @dpjtaylor, we will not be fixing this issue with fossa-cli v1 but I have created an internal ticket to once again support brew for the latest fossa-cli version (ANE-340 internally).
